"""Canonical reject reasons.

Reject reasons are part of the audit surface and should remain stable.
"""


class RejectReason:
    """Canonical reject reasons.

    These strings form part of the audit surface and should remain stable.
    """

    TRADING_DISABLED = "TRADING_DISABLED"

    DUPLICATE_ID = "DUPLICATE_ID"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"

    EXCHANGE_ERROR = "EXCHANGE_ERROR"
    EXCHANGE_REJECT = "EXCHANGE_REJECT"

    INVALID_TS = "INVALID_TS"
    INVALID_INSTRUMENT = "INVALID_INSTRUMENT"
    INVALID_QTY = "INVALID_QTY"
    INVALID_LIMIT_PRICE = "INVALID_LIMIT_PRICE"
    NO_MID_FOR_MARKET = "NO_MID_FOR_MARKET"

    MAX_LOSS_DRAWDOWN = "MAX_LOSS_DRAWDOWN"
    MAX_LOSS_ROLLING = "MAX_LOSS_ROLLING"

    MAX_POSITION = "MAX_POSITION"
    MAX_SINGLE_ORDER_NOTIONAL = "MAX_SINGLE_ORDER_NOTIONAL"
    MAX_GROSS_NOTIONAL = "MAX_GROSS_NOTIONAL"

    MAX_ACTIVE_QUOTES = "MAX_ACTIVE_QUOTES"
    MAX_GROSS_QUOTE_NOTIONAL = "MAX_GROSS_QUOTE_NOTIONAL"
    MAX_NET_QUOTE_NOTIONAL = "MAX_NET_QUOTE_NOTIONAL"

    # Venue policy constraints
    POST_ONLY_WOULD_TRADE = "POST_ONLY_WOULD_TRADE"
    MIN_NOTIONAL = "MIN_NOTIONAL"
